#!/bin/sh
#TROJAN_HOST=
#TROJAN_PASS=

iface()
{
	sdev=`route get example.com 2> /dev/null | grep interface`
	sdev=${sdev:13}
	while read -r line; do
		echo $line | grep $sdev > /dev/null 2>&1
		if [ $? = 0 ]; then
			IFACE=${last_line:4}
			break
		fi
		last_line=$line
	done <<< "$(networksetup -listnetworkserviceorder)"

	if [ -z "$IFACE" ]; then
		>&2 echo "Could not find current service"
		exit 1
	fi	

	echo "Current interface: $IFACE"
}

usage()
{
	echo "Usage: $0 <[start]|restart|stop|status|update|help>"
	echo
	echo "$0 [-v[0-5]] <HOST> <PASS>"
	echo
	exit 0
}

start()
{
	iface
	networksetup -setsocksfirewallproxy $IFACE 127.0.0.1 1080

	[ ! -z $2 ] && TROJAN_HOST=$2
	[ ! -z $3 ] && TROJAN_PASS=$3
	echo "{\"local_addr\":\"0.0.0.0\",\"local_port\":1080,\"remote_addr\":\"$TROJAN_HOST\",\"remote_port\":443,\"password\":[\"$TROJAN_PASS\"],\"log_level\":$1,\"ssl\":{\"verify\":false}}" > /tmp/trojan.conf
	if [ $1 -ge 4 ]; then
		nohup trojan -c /tmp/trojan.conf &> /tmp/trojan.log &
	elif [ $1 -ge 2 ]; then
		trojan -c /tmp/trojan.conf &
	else
		trojan -c /tmp/trojan.conf
		networksetup -setsocksfirewallproxystate $IFACE off
	fi
}

stop()
{
	iface
	networksetup -setsocksfirewallproxystate $IFACE off
	killall trojan
}

status()
{
	tail -f /tmp/trojan.log
}

case "$1" in
	start)
		start 2 $2 $3
		;;
	stop)
		stop
		;;
	restart)
		stop
		start 2 $2 $3
		;;
	s|status)
		status $2
		;;
	-v0|-v1|-v2|-v3|-v4|-v5)
		start ${1:2} $2 $3 $4 $5
		;;
	-v)
		start 1 $2 $3
		;;
	-h|help)
		usage
		;;
	*)
		start 5 $1 $2
		;;
esac


