#!/bin/sh

str_cut()
{
	if [ -z "$4" ]; then
		export $1=
		export $2=
	elif [[ "$4" =~ "$3" ]]; then
		export $1=${4%%"$3"*}
		export $2=${4#*"$3"}
	elif [[ $5 == R ]]; then
		export $1=
		export $2="$4"
	else
		export $1="$4"
		export $2=
	fi
}

str_split()
{
	local _PARAMS=(${3//$1/ })
	for _PARAM in ${_PARAMS[@]}; do
		str_cut KEY VAL $2 $_PARAM
		export $KEY=$VAL
		echo "  $KEY=$VAL"
	done
}

url_parse()
{
	str_cut _PROTO _PART : "$1" R
	[[ $_PART == //* ]] && _PART=${_PART:2}
	#echo PROTO=$_PROTO
	uri_parse $_PART
}

uri_parse()
{
	str_cut _PART _HASH \# $1
	str_cut _SERV_PATH _QUERY ? $_PART
	str_split \& = $_QUERY
	str_cut _SERV _PATH / $_SERV_PATH
	str_cut _USER_PASS _HOST_PORT @ "$_SERV" R
	str_cut  _USER _PASS : $_USER_PASS
	str_cut _HOST _PORT : $_HOST_PORT

	#echo HASH=$_HASH
	#echo SERV_PATH=$_SERV_PATH
	#echo QUERY=$_QUERY
	#echo PATH=$_PATH
	#echo USER=$_USER
	#echo PASS=$_PASS
	#echo HOST=$_HOST
	#echo PORT=$_PORT	
}

usage()
{
	echo "Usage: $0 <[start]|restart|stop|status|update|help>"
	echo
	echo "$0 [-v[0-5]] <XWING_URL>"
	echo
}

iface()
{
	sdev=`route get example.com 2> /dev/null | grep interface`
	sdev=${sdev:13}
	while read -r line; do
		echo $line | grep $sdev > /dev/null 2>&1
		if [ $? = 0 ]; then
			IFACE=${last_line:4}
			break
		fi
		last_line=$line
	done <<< "$(networksetup -listnetworkserviceorder)"

	if [ -z "$IFACE" ]; then
		>&2 echo "Could not find current service"
		exit 1
	fi	
}


start()
{
	if [ ! -z $2 ]; then
		local XURL=$2
	elif [ ! -z $XWING_URL ]; then
		local XURL=$XWING_URL
	else
		usage
		return
	fi

	iface
	echo "Local Network: $IFACE"

	url_parse $XURL

	if [[ $_PROTO == socks5 || $_PROTO == http || $_PROTO == https ]]; then
		PROXY_PROTO=$_PROTO
		PROXY_HOST=$_HOST
		PROXY_PORT=$_PORT
	else
		echo "Remote $XURL"
		PROXY_PROTO=socks5
		PROXY_HOST=127.0.0.1
		PROXY_PORT=1080
	fi

	if [ $_PROTO == http ]; then
		PROXY_TYPE=web
	elif [ $_PROTO == https ]; then
		PROXY_TYPE=secureweb
	else
		PROXY_TYPE=socksfirewall
	fi

	echo "export ALL_PROXY=$PROXY_PROTO://$PROXY_HOST:$PROXY_PORT"
	networksetup -set${PROXY_TYPE}proxy $IFACE $PROXY_HOST $PROXY_PORT

	[ -z $_PORT ] && _PORT=443
	if [ $_PROTO == trojan ]; then
		XCMD="trojan -c /tmp/trojan.conf"
	elif [ $_PROTO == ss ]; then
		if [ -z $_USER ]; then
			uri_parse `echo $_HOST | base64 -D`
		elif [ -z $_PASS ]; then
			str_cut _USER _PASS : `echo $_USER | base64 -D`
		fi
		XCMD="ss-local -s c$_HOST -p $_PORT -k $_PASS -l 1080 -m $_USER"
	else
		return
	fi

	if [ $1 -ge 2 ]; then
		nohup "$XCMD" &> /tmp/xwing.log &
	else
		$XCMD
		networksetup -setwebproxystate $IFACE off
		networksetup -setsecurewebproxystate $IFACE off
		networksetup -setsocksfirewallproxystate $IFACE off
	fi
}

stop()
{
	iface
	networksetup -setwebproxystate $IFACE off
	networksetup -setsecurewebproxystate $IFACE off
	networksetup -setsocksfirewallproxystate $IFACE off
	if [ -f /tmp/trojan.conf ]; then
		rm /tmp/trojan.conf
		killall trojan
	fi
}

status()
{
	tail -f /tmp/xwing.log
}

case "$1" in
	-h|help)
		usage
		;;
	start)
		start 2 $2
		;;
	stop)
		stop
		;;
	restart)
		stop
		start 2 $2
		;;
	s|status)
		status
		;;
	-v0|-v1|-v2|-v3|-v4|-v5)
		start ${1:2} $2
		;;
	-v)
		start 0 $2
		;;
	*)
		start 1 "$1"
		;;
esac
